### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by Prexerex** [cyberofficial/Synthalingua#111]
When running livetranslation.bat it gave me an error

"A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\transcribe_audio.py", line 869, in <module>
    main()
  File "C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\transcribe_audio.py", line 214, in main
    device = torch.device(args.device)
C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\transcribe_audio.py:214: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device = torch.device(args.device)
Using device: cpu
Microphone set to: Voicemeeter Out B1 (VB-Audio Vo
Now using ram flag: 1gb
Loading model tiny...
Loading model tiny instead since target language is not English...
Traceback (most recent call last):
  File "C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\transcribe_audio.py", line 869, in <module>
    main()
  File "C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\transcribe_audio.py", line 375, in main
    audio_model = whisper.load_model(model, device=device, download_root="models")
  File "C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\data_whisper\lib\site-packages\whisper\__init__.py", line 154, in load_model
    model.set_alignment_heads(alignment_heads)
  File "C:\Users\Prexe\Downloads\Synthalingua-master\Synthalingua-master\data_whisper\lib\site-packages\whisper\model.py", line 251, in set_alignment_heads
    mask = torch.from_numpy(array).reshape(
RuntimeError: Numpy is not available"

(live translation args: python transcribe_audio.py --microphone_enabled true --set_microphone 1 --device cpu --ram 1gb --record_timeout 2 --language ja --energy_threshold 500)

**Comment by cyberofficial** [comment]
Hello thank you for the report, I will investigate and report back soon.

For clarification did you run the setup file?

**Comment by cyberofficial** [comment]
Hello! Could you please try this command in the python environment? `pip install numpy==1.26.4`

To activate the the python environment, open a command prompt window to the Synthalingua Folder, type the command "`data_whisper\Scripts\activate`" press enter, then do "`pip install numpy==1.26.4`"

Should look like this
![image](https://github.com/cyberofficial/Synthalingua/assets/19499442/18ab62f5-624f-40e2-a908-2bea42cb6b01)

then run the pip install command, and retry the python command again

**Comment by Prexerex** [comment]
Worked!
