### ISSUE TITLE
Missing modules on Linux install

### ISSUE THREAD

**Issue by riuneko** [cyberofficial/Synthalingua#117]
Hey I'm back :D 

I went ahead and partitioned my drive for a Kubuntu dual-boot and grabbed a fresh install. Setup using the bash file in a Python 3.10 venv. Unfortunately I ran into this problem:

```
(venv_with_python3.10) riuneko@ubuntu:~/synth$ python transcribe_audio.py --ram 12gb --stream_translate --stream_language Japanese --stream https://www.youtube.com/watch?v=UFTu6GnwB5I
Loading Primary Imports
Error Loading Primary Imports
Check to make sure you have all the required modules installed.
Error: No module named 'speech_recognition'
Error Loading Primary Imports
Check the Modules folder for the imports.py file and make sure it is not missing or corrupted.
name 'sys' is not defined
Traceback (most recent call last):
  File "/home/riuneko/synth/modules/imports.py", line 6, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riuneko/synth/transcribe_audio.py", line 3, in <module>
    from modules.imports import *
  File "/home/riuneko/synth/modules/imports.py", line 54, in <module>
    sys.exit(1)
NameError: name 'sys' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riuneko/synth/transcribe_audio.py", line 9, in <module>
    sys.exit(1)
NameError: name 'sys' is not defined
```

Running `pip install SpeechRecognition` seems to download something, and I can repeat it each time until it breaks on pyaudio saying it failed building wheel for pyaudio.
Would using an older Kubuntu version based on 3.10 help if it wouldn't require a venv workaround?

Update 1: Okay actually I just chased every missing module and installed it through pip 😂 Figuring out ROCm now. Got pytorch with ROCm through their website 

Update 2: it might be working..

**Comment by riuneko** [comment]
Ignore me, I somehow made it work :D 
Thank you for the program!!!
