### ISSUE TITLE
Audio source must be entered before adjusting

### ISSUE THREAD

**Issue by unusualgarment** [cyberofficial/Synthalingua#63]
I am trying to run your program and installed everything. I had trouble installing CUDA and only installed the Nsight VSE and runtime components. I disabled nsight systems, nsight compute, visual studio integration, physx, geforce experience, hd audio and display driver.

Anyway This is what I get when launching run.bat

You are already using the latest version.
Current version: 1.0.9986

Using device: cuda
CUDA device name: NVIDIA GeForce RTX 3060
VRAM available: 12287.375 MB
Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?
Traceback (most recent call last):
  File "transcribe_audio.py", line 643, in <module>
  File "transcribe_audio.py", line 212, in main
  File "speech_recognition\__init__.py", line 189, in __exit__
AttributeError: 'NoneType' object has no attribute 'close'
[57760] Failed to execute script 'transcribe_audio' due to unhandled exception!
Press any key to continue . . .

**Comment by cyberofficial** [comment]
Thanks. Can you open command prompt or power shell and run the command `nvidia-smi`

You should see something like this.
```bash
C:\Users\cyberofficial>nvidia-smi
Fri Oct 27 09:00:55 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.58                 Driver Version: 537.58       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti   WDDM  | 00000000:2D:00.0  On |                  Off |
| 35%   62C    P2             228W / 450W |  14967MiB / 24564MiB |     72%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

Also can you edit the run file to have `--device cpu` and see if that works. If so, you may need a reinstall your nvidia drivers if you are having cuda issues.

**Comment by unusualgarment** [comment]
nvidia-smi
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.23                 Driver Version: 536.23       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  | 00000000:0B:00.0  On |                  N/A |
|  0%   54C    P8              24W / 170W |   1961MiB / 12288MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2432    C+G   ...ys\WinUI3Apps\PowerToys.Peek.UI.exe    N/A      |
|    0   N/A  N/A      5428    C+G   ...rwolf\0.233.2.2\OverwolfBrowser.exe    N/A      |
|    0   N/A  N/A      9352    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A     10772    C+G   ...les\Microsoft OneDrive\OneDrive.exe    N/A      |
|    0   N/A  N/A     11128    C+G   ...al\Discord\app-1.0.9020\Discord.exe    N/A      |
|    0   N/A  N/A     12164    C+G   ...\PowerToys\PowerToys.FancyZones.exe    N/A      |
|    0   N/A  N/A     12196    C+G   ...nt.CBS_cw5n1h2txyewy\SearchHost.exe    N/A      |
|    0   N/A  N/A     12236    C+G   ...2txyewy\StartMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     12804    C+G   ...werToys\PowerToys.PowerLauncher.exe    N/A      |
|    0   N/A  N/A     14036    C+G   ...t.LockApp_cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     14168    C+G   ...m Files\Mozilla Firefox\firefox.exe    N/A      |
|    0   N/A  N/A     15352    C+G   ...werToys\PowerToys.ColorPickerUI.exe    N/A      |
|    0   N/A  N/A     15644    C+G   ...y Games\current\service\Service.exe    N/A      |
|    0   N/A  N/A     16092    C+G   ...ekyb3d8bbwe\PhoneExperienceHost.exe    N/A      |
|    0   N/A  N/A     16136    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     16792    C+G   ...on\118.0.2088.69\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     17648    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     18036    C+G   ...inaries\Win64\EpicGamesLauncher.exe    N/A      |
|    0   N/A  N/A     19488    C+G   ...ne\Binaries\Win64\EpicWebHelper.exe    N/A      |
|    0   N/A  N/A     21220    C+G   ...Mozilla Thunderbird\thunderbird.exe    N/A      |
|    0   N/A  N/A     21304    C+G   ...\cef\cef.win7x64\steamwebhelper.exe    N/A      |
|    0   N/A  N/A     21660    C+G   ...crosoft\Edge\Application\msedge.exe    N/A      |
|    0   N/A  N/A     21856    C+G   ...ces\Razer Central\Razer Central.exe    N/A      |
|    0   N/A  N/A     23564    C+G   Z:\Overwolf\Overwolf.exe                  N/A      |
|    0   N/A  N/A     24220    C+G   ... Synapse 3 Host\Razer Synapse 3.exe    N/A      |
|    0   N/A  N/A     24392    C+G   ...52.0_x64__8wekyb3d8bbwe\GameBar.exe    N/A      |
|    0   N/A  N/A     24668    C+G   ...\iCloud\WebView2\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     25864    C+G   ...1.0_x64__8wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A     25908    C+G   ...siveControlPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     26488    C+G   ...m Files\Mozilla Firefox\firefox.exe    N/A      |
|    0   N/A  N/A     29172    C+G   C:\Program Files\NordVPN\NordVPN.exe      N/A      |
|    0   N/A  N/A     29964    C+G   ...on\118.0.2088.69\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     32496    C+G   ...Cloudflare WARP\Cloudflare WARP.exe    N/A      |
|    0   N/A  N/A     32724    C+G   ...on\118.0.2088.69\msedgewebview2.exe    N/A      |
+---------------------------------------------------------------------------------------+
```

run.bat
```

> Check ENV Module Loaded
> Checking if you are in a virtual environment...
> 
> 
> Checking if portable version is being used...
> Portable version detected, continuing with script...
> 
> 
> Loading Primary Imports
> Loading Extensions
> Version Checker Module Loaded
> Model Downloader Module Loaded
> Discord Module Loaded
> Console Settings Module Loaded
> Warnings Module Loaded
> Languages Module Loaded
> Args Module Loaded
> Web Server Module Loaded
> Extensions Loaded
> 
> 
> 
> 
> Checking for updates...
> You are already using the latest version.
> Current version: 1.0.9986
> 
> 
> 
> Using device: cpu
> Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?
> Traceback (most recent call last):
>   File "transcribe_audio.py", line 643, in <module>
>   File "transcribe_audio.py", line 212, in main
>   File "speech_recognition\__init__.py", line 189, in __exit__
> AttributeError: 'NoneType' object has no attribute 'close'
> [25156] Failed to execute script 'transcribe_audio' due to unhandled exception!
> Press any key to continue . . .
```
I'm gonna leave CUDA alone for now because I think it's gonna take a lot to troubleshoot why it fails to install the other parts. Unless you think the Nsight systems, Nsight compute, and Visual studio integration is necessary.

**Comment by cyberofficial** [comment]
Hmmmm one last thing to try, can you see if adding `--mic_calibration_time 1` to the flag list?

As for the cuda thing, generally everything should be installed as most of the time they piggy back off each other.

**Comment by unusualgarment** [comment]
```
Checking for updates...
You are already using the latest version.
Current version: 1.0.9986



Mic calibration flag detected.

Press [enter] when ready to start mic calibration.
Make sure there is no one speaking during this time.
Waiting for user input...
```
When i press ENTER
```

Starting mic calibration...
Traceback (most recent call last):
  File "transcribe_audio.py", line 111, in mic_calibration
  File "speech_recognition\__init__.py", line 383, in adjust_for_ambient_noise
AssertionError: Audio source must be entered before adjusting, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transcribe_audio.py", line 643, in <module>
  File "transcribe_audio.py", line 136, in main
  File "transcribe_audio.py", line 110, in mic_calibration
  File "speech_recognition\__init__.py", line 189, in __exit__
AttributeError: 'NoneType' object has no attribute 'close'
[24236] Failed to execute script 'transcribe_audio' due to unhandled exception!
Press any key to continue . . .
```

**Comment by cyberofficial** [comment]
Okay, narrows stuff down a whole lot.

Do you have any microphone sources or loop back devices? The error that is occurring means you do not have default microphones set that are capable of recording through software.

Make sure you have microphone access enabled like so.
![ApplicationFrameHost_4fy7411wD8](https://github.com/cyberofficial/Synthalingua/assets/19499442/e8f424fd-a10c-4bdd-8602-3fa1b48c53e8)

in sound settings, make sure have chosen a default micrphone
![Uploading ApplicationFrameHost_JjvfhLgrIe.png…]()

**Comment by unusualgarment** [comment]
Thanks, my microphone was off. It worked after turning it on. I installed Voicemeeter as well to pick up my desktop audio. 
I believe these two things should prob in some faq somewhere for those with no experience like me with this stuff.

**Comment by cyberofficial** [comment]
Thanks for the replies and being patient with me. if you have any more errors, feel free to create a new issue. 

I will implement a warning system for users with out microphones in the next update soon to be released.
