### ISSUE TITLE
value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by llamasensei7746** [cyberofficial/Synthalingua#78]
When I run the Run button in "Synthalingua_Wrapper"
it displays
""System.ArgumentNullException: value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Synthalingua_Wrapper.MainUI.RunScript_Click(Object sender, EventArgs e) in X:\github\Real-Time-Translation\Synthalingua_Wrapper\ MainUI.vb:line 130
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)" and I use the microphone option".

And I use the "Get IDs" in the microphone option also shows "The value cannot be null. (parameter 'path1')"

I have installed the recommended versions of Python and Git.
I'm using an AMD gpu, but I usually run on a Cpu.

I know I'm probably a computer noob, but I've been trying for a long time and I still don't understand it, so I just had to come here and ask!
![image](https://github.com/cyberofficial/Synthalingua/assets/119572783/07b5a5da-ab20-471b-ba77-7c755cd0bb55)

**Comment by cyberofficial** [comment]
Hello! Thank you for making this report, I will investigate it.

**Comment by cyberofficial** [comment]
I've found issue, and will be fixing in the next minor update.

**Comment by cyberofficial** [comment]
Hello! You can now download the update here: https://github.com/cyberofficial/Synthalingua/releases/tag/1.0.9996
